/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("com.github.nmhillusion:n2mix-java:2024.6.0") {
        exclude(group = "org.springframework", module = "*")
        exclude(group = "com.zaxxer", module = "*")
        exclude(group = "jakarta.servlet", module = "*")
        exclude(group = "com.fasterxml.jackson.core", module = "*")
        exclude(group = "org.hibernate.orm", module = "*")
        exclude(group = "com.google.firebase", module = "*")
        exclude(group = "org.ehcache", module = "*")
        exclude(group = "com.squareup.okhttp3", module = "*")
        exclude(group = "org.apache.poi", module = "*")
        exclude(group = "com.oracle.database.jdbc", module = "*")
        exclude(group = "org.apache.pdfbox", module = "*")
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }

}

application {
    // Define the main class for the application.
    mainClass = "tech.nmhillusion.local_dependency_builder.MainKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}